producer:
  key.serializer: org.apache.kafka.common.serialization.StringSerializer
  value.serializer: org.apache.kafka.common.serialization.StringSerializer
  bootstrap.servers: localhost:29092,127.0.0.1:29092
  topic: confirm
  acks: -1
  partitioner.class: sbp.school.kafka.service.KafkaProducerPartitionerService
  id: 1